//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHCIQuizSolution.DBContext.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserQuestion()
        {
            this.QuizUsers = new HashSet<QuizUser>();
        }
    
        public string id { get; set; }
        public string questionId { get; set; }
        public string selectedOptionIds { get; set; }
        public Nullable<bool> isCorrect { get; set; }
        public Nullable<int> index { get; set; }
    
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizUser> QuizUsers { get; set; }
    }
}
