//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHCIQuizSolution.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizUser
    {
        public string id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string currentUserQuizId { get; set; }
        public string currentUserQuestionId { get; set; }
        public Nullable<bool> isLastQuiz { get; set; }
        public Nullable<bool> isLastQuestionForCurrentQuiz { get; set; }
    
        public virtual UserQuestion CurrentUserQuestion { get; set; }
        public virtual UserQuiz CurrentUserQuiz { get; set; }
    }
}
