//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHCIQuizSolution.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizOption
    {
        public string id { get; set; }
        public string questionId { get; set; }
        public string description { get; set; }
        public Nullable<bool> isCorrect { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
