/*
Deployment script for D:\IMP\GHCI\NETPROJECT\GHCIQUIZSOLUTION\GHCIQUIZSOLUTION\APP_DATA\GHCIQUIZ.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\IMP\GHCI\NETPROJECT\GHCIQUIZSOLUTION\GHCIQUIZSOLUTION\APP_DATA\GHCIQUIZ.MDF"
:setvar DefaultFilePrefix "D_\IMP\GHCI\NETPROJECT\GHCIQUIZSOLUTION\GHCIQUIZSOLUTION\APP_DATA\GHCIQUIZ.MDF_"
:setvar DefaultDataPath "C:\Users\Joseph A\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\Joseph A\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_SHRINK OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ENABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
PRINT N'Dropping [dbo].[FK_Question_Quiz]...';


GO
ALTER TABLE [dbo].[Question] DROP CONSTRAINT [FK_Question_Quiz];


GO
PRINT N'Dropping [dbo].[FK_QuizOption_Question]...';


GO
ALTER TABLE [dbo].[QuizOption] DROP CONSTRAINT [FK_QuizOption_Question];


GO
PRINT N'Dropping [dbo].[FK_QuizUser_UserQuestion]...';


GO
ALTER TABLE [dbo].[QuizUser] DROP CONSTRAINT [FK_QuizUser_UserQuestion];


GO
PRINT N'Dropping [dbo].[FK_QuizUser_UserQuiz]...';


GO
ALTER TABLE [dbo].[QuizUser] DROP CONSTRAINT [FK_QuizUser_UserQuiz];


GO
PRINT N'Dropping [dbo].[FK_UserQuestion_Question]...';


GO
ALTER TABLE [dbo].[UserQuestion] DROP CONSTRAINT [FK_UserQuestion_Question];


GO
PRINT N'Dropping [dbo].[FK_UserQuestion_UserQuiz]...';


GO
ALTER TABLE [dbo].[UserQuestion] DROP CONSTRAINT [FK_UserQuestion_UserQuiz];


GO
PRINT N'Dropping [dbo].[FK_UserQuiz_Quiz]...';


GO
ALTER TABLE [dbo].[UserQuiz] DROP CONSTRAINT [FK_UserQuiz_Quiz];


GO
PRINT N'Dropping [dbo].[FK_UserQuiz_QuizUser]...';


GO
ALTER TABLE [dbo].[UserQuiz] DROP CONSTRAINT [FK_UserQuiz_QuizUser];


GO
PRINT N'Dropping [dbo].[AK_Quiz_Level]...';


GO
ALTER TABLE [dbo].[Quiz] DROP CONSTRAINT [AK_Quiz_Level];


GO
PRINT N'Dropping [dbo].[CK_Quiz_Complex]...';


GO
ALTER TABLE [dbo].[Quiz] DROP CONSTRAINT [CK_Quiz_Complex];


GO
PRINT N'Dropping [dbo].[CK_Quiz_Desc]...';


GO
ALTER TABLE [dbo].[Quiz] DROP CONSTRAINT [CK_Quiz_Desc];


GO
PRINT N'Dropping [dbo].[CK_QuizUser_Email]...';


GO
ALTER TABLE [dbo].[QuizUser] DROP CONSTRAINT [CK_QuizUser_Email];


GO
PRINT N'Dropping [dbo].[CK_QuizUser_Name]...';


GO
ALTER TABLE [dbo].[QuizUser] DROP CONSTRAINT [CK_QuizUser_Name];


GO
PRINT N'Creating [gd_execprocs]...';


GO
CREATE ROLE [gd_execprocs]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [ghci]...';


GO
CREATE USER [ghci] WITHOUT LOGIN
    WITH DEFAULT_SCHEMA = [ghci];


GO
REVOKE CONNECT TO [ghci];


GO
PRINT N'Creating <unnamed>...';


GO
EXECUTE sp_addrolemember @rolename = N'db_backupoperator', @membername = N'ghci';


GO
PRINT N'Creating <unnamed>...';


GO
EXECUTE sp_addrolemember @rolename = N'db_datareader', @membername = N'ghci';


GO
PRINT N'Creating <unnamed>...';


GO
EXECUTE sp_addrolemember @rolename = N'db_datawriter', @membername = N'ghci';


GO
PRINT N'Creating <unnamed>...';


GO
EXECUTE sp_addrolemember @rolename = N'db_ddladmin', @membername = N'ghci';


GO
PRINT N'Creating <unnamed>...';


GO
EXECUTE sp_addrolemember @rolename = N'db_securityadmin', @membername = N'ghci';


GO
PRINT N'Creating [ghci]...';


GO
CREATE SCHEMA [ghci]
    AUTHORIZATION [ghci];


GO
PRINT N'Update complete.';


GO
